import { z } from 'zod';

const shortText = z.string().trim().max(200);
const longText = z.string().trim().max(5_000);

export const memberSchema = z.object({
  id: z.string().trim().min(1).max(128),
  ownerUid: z.string().trim().min(1).max(128),
  firstName: z.string().trim().min(1).max(100),
  lastName: z.string().trim().max(100),
  fullName: z.string().trim().min(1).max(200),
  fullNameTa: z.string().trim().max(200).optional(),
  preferredLanguage: z.enum(['en', 'ta']).optional(),
  email: z.string().trim().email().max(150),
  phone: z.string().trim().max(30),
  dob: z.string().trim().max(40),
  gender: shortText,
  relationship: shortText,
  bloodGroup: z.string().trim().max(20),
  diocese: shortText,
  parish: shortText,
  parishPriest: shortText,
  country: z.string().trim().max(100),
  currentAddress: longText,
  permanentAddress: longText.optional(),
  address: z.object({
    street: longText,
    city: shortText,
    state: shortText,
    zipCode: z.string().trim().max(20),
    country: z.string().trim().max(100),
  }),
  membershipClass: z.enum(['Active', 'Guest', 'VIP', 'Staff', 'Alumnus', 'Director', 'Seminarian', 'Student']),
  education: shortText.optional(),
  profession: shortText.optional(),
  instagram: z.string().trim().max(500).optional(),
  facebook: z.string().trim().max(500).optional(),
  igPages: z.string().trim().max(1_000).optional(),
  fbPages: z.string().trim().max(1_000).optional(),
  ytChannels: z.string().trim().max(1_000).optional(),
  ambition: longText,
  biographyDraft: longText.optional(),
  biographyDrafts: z.object({
    short: longText,
    professional: longText,
    ministry: longText,
    tamil: longText,
  }).optional(),
  hobbies: longText,
  fiveYears: longText.optional(),
  achievements: longText.optional(),
  ideas: longText.optional(),
  roles: longText.optional(),
  bibleBook: shortText.optional(),
  bibleChapter: z.string().trim().max(20).optional(),
  bibleVerse: z.string().trim().max(20).optional(),
  bibleVerseText: longText.optional(),
  bibleVerseWhy: longText.optional(),
  techSkills: z.array(shortText).max(100),
  softSkills: z.array(shortText).max(100),
  goals: z.array(shortText).max(100),
  support: z.array(shortText).max(100),
  frequency: shortText.optional(),
  mode: shortText.optional(),
  photoURL: z.string().trim().max(2_048).optional(),
  pledgesAccepted: z.boolean(),
  joinedDate: z.string().trim().max(50),
  status: z.enum([
    'Pending',
    'Affiliated',
    'Abdicated',
    'Director',
    'Inactive',
    'Active',
    'Suspended',
    'ID card to be provided',
    'Data Insufficient',
  ]),
  avatarUrl: z.string().trim().max(200),
  notes: longText,
  customFields: z.array(z.object({
    key: shortText,
    value: longText,
  })).max(100),
  lastActive: z.string().trim().max(50),
  voxUserId: z.string().trim().max(150).optional(),
  privacyConsent: z.object({
    showPhoto: z.boolean(),
    showLocation: z.boolean(),
    showSocialProfiles: z.boolean(),
    showBiography: z.boolean(),
    showSkills: z.boolean(),
    showTamilName: z.boolean(),
    acceptedAt: z.string().trim().max(50),
    version: z.literal('2026-01'),
  }).optional(),
});

export type ValidatedMember = z.infer<typeof memberSchema>;
